In [1]:
import numpy as np

a_ndarray = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [7, 8, -9]
])

b_ndarray = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

In [2]:
result = np.matmul(a_ndarray, b_ndarray)

print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
# Problem 2: Matrix product using NumPy

result_matmul = np.matmul(a_ndarray, b_ndarray)

result_dot = np.dot(a_ndarray, b_ndarray)

result_at = a_ndarray @ b_ndarray

print("Using np.matmul():")
print(result_matmul)

print("\nUsing np.dot():")
print(result_dot)

print("\nUsing @ operator:")
print(result_at)

Using np.matmul():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
# Problem 3: Calculate one element of the matrix product

c_00 = 0

for k in range(3):
    c_00 += a_ndarray[0, k] * b_ndarray[k, 0]

print("C[0, 0] =", c_00)

C[0, 0] = 6


In [6]:
# Problem 4: Scratch implementation of matrix multiplication

def matrix_product(a, b):
    # Check that the matrices can be multiplied
    if a.shape[1] != b.shape[0]:
        raise ValueError("The number of columns in A must equal the number of rows in B.")

    # Create a result matrix filled with zeros
    result = np.zeros((a.shape[0], b.shape[1]))

    # Calculate each element of the result
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]

    return result


# Calculate A × B
result = matrix_product(a_ndarray, b_ndarray)

print(result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [7]:
# Problem 5: Check whether matrix multiplication is defined

def matrix_product(a, b):
    # Check that both inputs are 2-dimensional
    if a.ndim != 2 or b.ndim != 2:
        raise ValueError(
            f"Both inputs must be 2-dimensional. "
            f"Got shapes {a.shape} and {b.shape}."
        )

    # Check that the matrix product is defined
    if a.shape[1] != b.shape[0]:
        raise ValueError(
            f"Matrix multiplication is not defined for shapes "
            f"{a.shape} and {b.shape}."
        )

    # Create the result matrix
    result = np.zeros((a.shape[0], b.shape[1]))

    # Calculate the matrix product
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]

    return result

In [8]:
d_ndarray = np.array([
    [-1, 2, 3],
    [4, -5, 6]
])

e_ndarray = np.array([
    [-9, 8, 7],
    [6, -5, 4]
])

matrix_product(d_ndarray, e_ndarray)

ValueError: Matrix multiplication is not defined for shapes (2, 3) and (2, 3).

In [9]:
result = matrix_product(a_ndarray, b_ndarray)

print(result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [10]:
# Problem 6: Transposition

# Transpose E
e_transposed = e_ndarray.T

# Calculate D × E.T
result_1 = np.matmul(d_ndarray, e_transposed)

print("D shape:", d_ndarray.shape)
print("E.T shape:", e_transposed.shape)

print("\nD × E.T:")
print(result_1)

print("Shape:", result_1.shape)


# Transpose D
d_transposed = d_ndarray.T

# Calculate D.T × E
result_2 = np.matmul(d_transposed, e_ndarray)

print("\nD.T shape:", d_transposed.shape)
print("E shape:", e_ndarray.shape)

print("\nD.T × E:")
print(result_2)

print("Shape:", result_2.shape)

D shape: (2, 3)
E.T shape: (3, 2)

D × E.T:
[[ 46  -4]
 [-34  73]]
Shape: (2, 2)

D.T shape: (3, 2)
E shape: (2, 3)

D.T × E:
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
Shape: (3, 3)
